package CPUSCHED;
import java.io.*;
import java.util.Random;

public class GenerateData {
    public static void main(String[] args) throws IOException {
        Random r = new Random(42); // fixed seed for reproducibility
        PrintWriter pw = new PrintWriter("datafile.txt"); // will be created in project root
        int arrival = 0;
        for (int i = 0; i < 500; i++) {
            arrival += r.nextInt(30);
            int burst = 1 + r.nextInt(50);
            pw.println(arrival + " " + burst);
        }
        pw.close();
        System.out.println("datafile.txt generated (500 processes)"); // This code generates a data file named "datafile.txt" containing 500 lines, each representing a process with its arrival time and burst time. The arrival times are generated by cumulatively adding a random integer between 0 and 29 to the previous arrival time, ensuring that the processes arrive in increasing order. The burst times are generated as random integers between 1 and 50. The use of a fixed seed (42) for the Random object ensures that the same data is generated each time the program is run, which can be useful for testing and debugging purposes.
    }
}